# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]
#
#exporters:
#  otlp:
#    endpoint: "http://10.160.0.5:4317"
#    tls:
#      insecure: true
# debug:
#    verbosity: detailed

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s

exporters:
  signozclickhousemetrics:
  signozclickhousetraces:
  signozclickhouselogs:

service:
  pipelines:

    metrics:
      receivers: [hostmetrics, docker_stats, otlp]
      exporters: [signozclickhousemetrics]

    traces:
      receivers: [otlp]
      exporters: [spanmetrics, signozclickhousetraces]

    logs:
      receivers: [otlp]
      exporters: [signozclickhouselogs]
